# Fetching the latest Node.js image on Alpine Linux
FROM node:20-alpine AS development

# Install openssl and ca-certificates, and update certificates
RUN apk add --no-cache openssl ca-certificates \
    && update-ca-certificates

# Declare environment variable
ENV NODE_ENV development

# Set up the working directory
WORKDIR /react-app

# Install dependencies
COPY ./package*.json /react-app/
RUN npm install

# Copy all project files
COPY . /react-app

# Start the application
CMD ["npm", "start"]
