# Fetching the latest node image on alpine linux
FROM node:alpine AS development

#missing cryptographic routines can be supplemented by installing the openssl and ca-certificates packages
RUN grep -rnw -e "update-ca-certificates" /etc/ssl/certs/

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
COPY ./package*.json /react-app

RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD ["npm","start"]